server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: lb://catalogue-service
          predicates:
            - Path=/catalogs/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka